<<<<<<<< HEAD:DRF_projects/myNoticeBoard/posts/migrations/0002_auto_20221019_0240.py
# Generated by Django 3.2 on 2022-10-18 17:40
========
# Generated by Django 3.2 on 2022-11-08 17:43
>>>>>>>> cd87ce6554b837886f616edcec499686b1826a9a:DRF_projects/myNoticeBoard/posts/migrations/0003_alter_post_author.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
<<<<<<<< HEAD:DRF_projects/myNoticeBoard/posts/migrations/0002_auto_20221019_0240.py
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_posts', to=settings.AUTH_USER_MODEL),
        ),
========
>>>>>>>> cd87ce6554b837886f616edcec499686b1826a9a:DRF_projects/myNoticeBoard/posts/migrations/0003_alter_post_author.py
    ]
