# Generated by Django 3.2 on 2022-10-10 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_complete',
            new_name='complete',
        ),
    ]
