/*
PARTITION TABLE
*/
--CREATE TABLE SALES(
--    PROD_ID NUMBER(6, 0) NOT NULL,
--    CUST_ID NUMBER(6, 0) NOT NULL,
--    CHANNEL_ID NUMBER(6, 0) NOT NULL,
--    EMPLOYEE_ID NUMBER(6, 0) NOT NULL,
--    SALES_DATE DATE DEFAULT SYSDATE NOT NULL,
--    SALES_MONTH VARCHAR2(6),
--    QUANTITY_SOLD NUMBER(10, 2),
--    AMOUNT_SOLD NUMBER(10, 2),
--    CREATE_DATE DATE DEFAULT SYSDATE,
--    UPDATE_DATE DATE DEFAULT SYSDATE
--)
--PARTITION BY RANGE(SALES_MONTH)
--(
--    PARTITION SALES_Q1_2023 VALUES LESS THAN ('202304'),
--    PARTITION SALES_Q2_2023 VALUES LESS THAN ('202307'),
--    PARTITION SALES_Q3_2023 VALUES LESS THAN ('202310'),
--    PARTITION SALES_Q4_2023 VALUES LESS THAN ('202401')
--);

